name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm ci

    # Step 4: Create .env file from GitHub Secrets
    - name: Create .env file
      run: echo "${{ secrets.PROD_ENV_BACKEND }}" > .env

    # Step 5: Run tests (if you have any)
    - name: Run tests
      run: npm test
      if: false  # Remove this line if you have tests to run

    # Step 6: Build application (if needed)
    - name: Build
      run: npm run build
      if: false  # Remove this line if you have a build step